### ISSUE TITLE
Promijeni while petlju u for petlju

### ISSUE THREAD

**Issue by lukarolak** [Mirixy17/MindPower#1]
Kreiraj novu datoteku s nazivom "ispisivanje_rijeci_for_loop.cpp" te u njoj stavi kod koji zamijeni while petlju s for petljom od datoteke.

https://github.com/Mirixy17/MindPower/blob/master/3%20primjeri/ispisivanje_rijeci_while_loop.cpp

**Comment by Mirixy17** [comment]
Herr Lehrer, ich glaube, ich bin fertig!
