### ISSUE TITLE
Fizz buzz

### ISSUE THREAD

**Issue by lukarolak** [Mirixy17/MindPower#11]
Ovo je jednostavan zadatak, koji koristi sve sto smo do sada radili.

[Fizz Buzz](https://www.tomdalling.com/blog/software-design/fizzbuzz-in-too-much-detail/) je popularna igra među programerima koji zele dokazati da su 

> "the very best, like no one ever was.."

Ukratko za brojeve od **1 do 100** ispisi:

 1. "Fizz" ako je **broj dijeljiv s 3**
 2. "Buzz" ako je **broj dijeljiv s 5**
 3. "FizzBuzz" ako je **broj dijeljiv s 3 i s 5**

Inace ispisi broj.

Primjer:

1. 1
2. 2
3. Fizz
4. 4
5. Buzz
6. Fizz
7. 7
8. 8
9. Fizz
10. FizzBuzz
11. 11
...

**Comment by Mirixy17** [comment]
CINI MI SE DA OVO FUNKCIONIRA U C++ SHELLU; ALI U VISUAL STUDIJU ME ZEZA OPET, koliko sam ja do sada naucila/shvatila za visual studio: tamo samo izbacim int main() jer vec postoji header za to, bitno je da ubacim string jer nije dio C++ nego ga je netko stvorio - ono sto mi nije jasno jer da mi non stop napominje da u sintaksi nesto ne valja i da je ovo stara verzija nesto u tom smislu i sto god da mijenjam ne ide...


#include <iostream>
#include <string>

int main()
{
int broj = 14;

    bool djeljivsa3 = broj % 3 == 0;
    if (djeljivsa3)
    {
    std::cout << "Fizz";
    }

    bool djeljivsa5 = broj % 5 == 0;
    if (djeljivsa5)
{
     std::cout << "Buzz";
}
    bool djeljivsa3i5 = broj % 3 && 5 == 0;
    if (djeljivsa3i5)
    
    {
        std::cout << "FizzBuzz";
    }
    bool nijedjeljivs3i5 = broj % 5 && 3 != 0;
    
    if (nijedjeljivs3i5)
    {
    std::cout << broj;
}
}

**Comment by Mirixy17** [comment]
#pragma once
#include <iostream>

void FizzBuzz(int broj)

{
	if (broj % 5 == 0 && broj % 3 == 0)
	{
		std::cout << "fizzbuzz" << std::endl;
	}
	else if (broj % 5 == 0)
	{
		std::cout << "buzz" << std::endl;
	}
	else if (broj % 3 == 0)
	{
		std::cout << "fizz" << std::endl;
	}
	else
	{
		std::cout << broj << std::endl;
	}
}


/*provjera u for petlji

#include "FizzBuzz.h"
int main()
{
	for (int broj = 1; broj < 100; broj++)
		FizzBuzz(broj);
}

*/

**Comment by Mirixy17** [comment]
#include <iostream>
#include <string>
#include "Ispis.h"
#include <math.h>

int main()
{
	int broj = std::round(15);

	for (int broj = 1; broj < 100; broj++)
	{
		const bool djeljivS3 = broj % 3 == 0;
		const bool djeljivS5 = broj % 5 == 0;

		if (djeljivS3 && djeljivS5)
		{
			Ispis("FizzBuzz");
		}
		else if (djeljivS5)
		{
			Ispis("Buzz");
		}
		else if (djeljivS3)
		{
			Ispis("Fizz");
		}
		else
		{
			Ispis(broj);
		}
	}
}

**Comment by Mirixy17** [comment]
#pragma once
#include <string>

void Ispis(int broj);

void Ispis(std::string rijec);

void Ispis(float broj);

**Comment by Mirixy17** [comment]
#include "Ispis.h"
#include <iostream>

// Ispis ()

void Ispis(int broj)
{
	std::cout << broj<<"\n";
}

void Ispis(std::string rijec)
{

	std::cout << rijec<<"\n";
}

void Ispis(float broj)
{
	std::cout << broj<<"\n";
}

**Comment by Mirixy17** [comment]
```
// Tetris.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <Windows.h>
#include <chrono>
#include <thread>

void banana()
{
    std::chrono::seconds dura(10);
    std::this_thread::sleep_for(dura);
    system("cls");
}

void Ispis(std::string rijec)
{
    std::cout << rijec << "\n";
}

int main()
{
    const std::string granica   = "************";
    const std::string praznina  = "*           *";

    std::string polje;
    polje.append(granica);
    polje.append("\n");
    polje.append(praznina);
    polje.append("\n");
    polje.append(praznina);
    polje.append("\n");
    polje.append(praznina);
    polje.append("\n");
    polje.append(praznina);
    polje.append("\n");
    polje.append(granica);
    Ispis(polje);

    banana();
    
    Ispis("************\n*    *     *\n*          *\n*          *\n*          *\n*          *\n************");
    
    banana();

    Ispis("************\n*          *\n*    *     *\n*          *\n*          *\n*          *\n************");

    banana();

    Ispis("************\n*          *\n*          *\n*    *     *\n*          *\n*          *\n************");

    banana();

    Ispis("************\n*          *\n*          *\n*          *\n*    *     *\n*          *\n************");

    banana();

    Ispis("************\n*          *\n*          *\n*          *\n*          *\n*    *     *\n************");
}
```

**Comment by Mirixy17** [comment]
```
#include <iostream>
#include <string>
#include <math.h>

void Ispis(std::string rijec)

{
	std::cout << rijec << '\n';
}

void Ispis2(int broj)

{
	std::cout << broj << '\n';
}

int main()
{
	int broj = std::round(15);

	for (int broj = 1; broj < 100; broj++)
	{
		const bool djeljivS3 = broj % 3 == 0;
		const bool djeljivS5 = broj % 5 == 0;

		if (djeljivS3 && djeljivS5)
		{
			Ispis("FizzBuzz");
		}
		else if (djeljivS5)
		{
			Ispis("Buzz");
		}
		else if (djeljivS3)
		{
			Ispis("Fizz");
		}
		else
		{
			Ispis2(broj);
		}
	}
}
```
