### ISSUE TITLE
Implementiraj std::getline

### ISSUE THREAD

**Issue by lukarolak** [Mirixy17/MindPower#3]
`std::getline` je opisana ovako "`getline` reads characters from an input stream and places them into a string:"
`std::cin` radi istu stvar kao i `std::getline` samo getline consume-a white space-ove, sto znaci da mozemo s getline upisivati cijele recenice, umjesto individualnih rijeci s `std::cin`

Da vidis razliku izmedu *getline* i *cin* pokreni ovaj program:

    #include <string>
    #include <iostream>
    
    int main()
    {
    	std::cout << "std::getline primjer, upisi \"Anni Eisler Lehmann Strasse\"" << "\n";
    	std::string recenica;
    	std::getline(std::cin, recenica);
    	std::cout << recenica.c_str() << "\n";
    
    	std::cout << "std::cin primjer, upisi \"Anni Eisler Lehmann Strasse\"" << "\n";
    	std::string rijec;
    	std::cin >> rijec;
    	std::cout << rijec.c_str() << "\n";
    }

 `std::getline` je definiran unutar `<string>` header-a. Sto znaci da trebamo `#include` at taj header za koristenje std::getline funkcije.

Zadatak je napisati program koji ispisuje svako slovo u zasebni red iz recenice koju korisnik upise.

Korisni linkovi:

 1. [std::getline](https://de.cppreference.com/w/cpp/string/basic_string/getline)
 2. [Zasto nam treba #include](http://www.cplusplus.com/forum/articles/10627/) (Ovo je poprilicno advanced tema, koju cemo raditi kasnije, ali ako te zanima zasto nam sada treba #include \<string\>, to je zato jer je std::getline definiran unutar string headera. Jednako kao sto je `class MyClass` definirana u `myclass.h`  u njegovom primjeru)
 3. [std::string[] operator](http://www.cplusplus.com/reference/string/string/operator[]/)(Jako! korisno za procitati, probaj implementirati njihov primjer)

**Comment by Mirixy17** [comment]
// Ich glaube, ich bin fertig i usput sam ukapirala kako ubaciti ß

#include < string >
#include < iostream >

using namespace std;
namespace Umlaut

{
	const unsigned char ss = static_cast<unsigned char>(225);
}
int main()
{
	std::cout << " Eine \n Stra" << Umlaut::ss << "e \n Namens \n Hindenburg \n sollte \n nicht \n existieren" << "\n";
	std::string recenica;
	std::getline(std::cin, recenica);
	std::cout << recenica.c_str() << "\n";
	std::cout << " Eine \n Stra" << Umlaut::ss << "e \n Namens \n Hindenburg \n sollte \n nicht \n existieren" << "\n";
	std::string rijec;
	std::cin >> rijec;
	std::cout << rijec.c_str() << "\n";
}


// PS: ukapirati je isto germanizam, ali prvotno iz latinskog capere: https://www.duden.de/rechtschreibung/kapieren

**Comment by lukarolak** [comment]
Otvorio sam nam novi pull request tako da mozemo zajedno proci kroz code review.
[pull request](https://github.com/Mirixy17/MindPower/pull/4)

**Comment by lukarolak** [comment]
@Mirixy17  Sutra cemo proci zajedno kod i zadatak.
