### ISSUE TITLE
nedovrseni dijalog

### ISSUE THREAD

**Issue by Mirixy17** [Mirixy17/MindPower#9]
#include <iostream>
#include <string>

int main()
{
  std::string name;
  std::cout << "What is your name?";
  getline (std::cin, name);
  std::cout << "Hello, " << name << "!\n";
  
  std::string age;
  std::cout << "What is your age? ";
  getline (std::cin, age);
  std::cout << "How do you feel being " << age << "?\n"; 
  }

/* kako dodati na kraju jos ovu liniju:  
std::cout << "As a great man once said: ´I'm too old just to play, And too young to be quite without wishes.`";
nakon sto ispise "How do you feel being __?"

pokusala sam preko if isto ne ide jer ne moze saznati? koji je age da bi saznao je li veci/manji od 27

#include <iostream>
#include <string>

int main()

{
  std::string name;
  std::cout << "What is your name?";
  getline (std::cin, name);
  std::cout << "Hello, " << name << "!\n";
  
  std::string age;
  std::cout << "What is your age? ";
  getline (std::cin, age);
  std::cout << "How do you feel being " << age << "?\n"; 
}

  int age;
  age = 27;
  
  if (age <= 27)
  
  {
      
  std::cout << "As a great man once said: ´I'm too old just to play, And too young to be quite without wishes.`";
  
  }
  *\

**Comment by lukarolak** [comment]
Preko ove stranice sam uredio tvoje pitanje da mi je lakse citati
https://stackedit.io/app#

    #include  
    #include
    
    int main()  
    {  
    	std::string name;  
    	std::cout << "What is your name?";  
    	getline (std::cin, name);  
    	std::cout << "Hello, " << name << "!\n";
    
    	std::string age;  
    	std::cout << "What is your age? ";  
    	getline (std::cin, age);  
    	std::cout << "How do you feel being " << age << "?\n";  
    }

kako dodati na kraju jos ovu liniju:  

    std::cout << "As a great man once said: ´I'm too old just to play, And too young to be quite without wishes.`"; 

 
nakon sto ispise 

> "How do you feel being __?"

pokusala sam preko if isto ne ide jer ne moze saznati? koji je age da bi saznao je li veci/manji od 27

    #include  
    #include
    
    int main()
    {  
    	std::string name;  
    	std::cout << "What is your name?";  
    	getline (std::cin, name);  
    	std::cout << "Hello, " << name << "!\n";
    
    	std::string age;  
    	std::cout << "What is your age? ";  
    	getline (std::cin, age);  
    	std::cout << "How do you feel being " << age << "?\n";  
    }
    
    int age;  
    age = 27;
    if (age <= 27)
    {
    	std::cout << "As a great man once said: ´I'm too old just to play, And too young to be quite without wishes.`";
    }

**Comment by lukarolak** [comment]
Hmm, nisam previse siguran sto me zelis pitati.

> kako dodati na kraju jos ovu liniju:  
> 
> std::cout << "As a great man once said: ´I'm too old just to play, And
> too young to be quite without wishes.`";

Ovdje sam jednostavno dodao ispis na kraju tvoga programa, no ne cini mi se da si to htjela
[primjer No.1](https://github.com/Mirixy17/MindPower/commit/38c6cf5b5e29e088445cfb6155fefe99b454f011#diff-452ff4dfadd1b56b216cbdecbcf280dd)

> pokusala sam preko if isto ne ide jer ne moze saznati? koji je age da
> bi saznao je li veci/manji od 27

Sto ne moze saznati? Sto zelis ispitati/uciniti s if tvrdnjom?

**Comment by Mirixy17** [comment]
skuzila sam da su ovi znakovi `` u citatu bili krivi zato sto mi nije nikako htio ispisati zadnju recenicu, zato sam pokusala onda preko IF jer nisam vidjela gresku (nije mi uopce ni pokazao da se ne moze koristiti '' na tom mjestu), sada vidim da je jednostavno, no svejedno me zanima i dalje moze li kod prepoznati ono sto mi unesemo direktno preko CIN i iskoristiti to za daljnji tijek koda, mozda sad previse kompliciram nepotrebno, samo me zanimalo postoje li takve mogucnosti,

Osim toga vratila sam se C++ Shell jer s njim nikad nemam problema, a sa VS non stop.

**Comment by lukarolak** [comment]
Sada razumijem sto mi zelis reci.

Ovaj kod ne ce raditi

    std::cout << "Luka je rekao: "Bok!"";
jer znak `"` koji je ispred slova 'B' zavrsava string `"Luka je rekao "`.
Sjecas se da smo za prelazenje u novi red koristili znak `'\n'`. To je specijalni znak koji govori racunalu da teks prelazi u novi red.
Ti specijalni znakovi ispred sebe imaju znak `'\'`.

U tvome slucaju zelis nekako reci c++ -u da znak `"` ne predstavlja pocetak ili  kraj stringa, vec da je on samo znak, kao i bilo koje drugo slovo.

To ces uciniti  koristeci specijalni znak `'\"'` 

Ovaj kod ce uciniti sto zelis(isprobaj ga)

    std::cout << "Luka je rekao: \"Bok!\"";
Preporucio bih ti da isprobas sve escape sequences kako ih programeri zovu za bolje razumijevanje teme. Ovo je jako bitno znanje koje ja koristim skoro na dnevnoj bazi, stoga mislim da ce ti biti jako korisno.
[https://en.cppreference.com/w/c/language/escape](https://en.cppreference.com/w/c/language/escape)

Ako zapnes kod nekog escape znaka, probaj koristiti druge. Sve koje ne mozes implementirati cemo proci zajedno.
